# Stormcraft-Essence Configuration

# Ability Requirements and Settings
abilities:
  # Passive Abilities
  storm_resistance:
    unlock_level: 10
    # Damage reduction % per SEL (at unlock level)
    base_reduction_percent: 5.0
    # Additional reduction per SEL above unlock
    per_level_bonus: 0.5
    # Maximum reduction cap
    max_reduction_percent: 50.0

  lightning_reflexes:
    unlock_level: 15
    # Speed amplifier at unlock level (0 = Speed I, 1 = Speed II, etc)
    base_speed_amplifier: 0
    # Additional amplifier per 10 SEL above unlock
    per_10_levels_bonus: 1
    # Maximum speed amplifier cap
    max_speed_amplifier: 3

  stormborn:
    unlock_level: 20
    # Health regen per tick at unlock level (1.0 = half heart per second)
    base_regen_amount: 0.5
    # Additional regen per 5 SEL above unlock
    per_5_levels_bonus: 0.1
    # Maximum regen cap
    max_regen_amount: 2.0

  stormrider:
    unlock_level: 100
    # Stormrider is free - no essence drain
    # Allows gliding and fall damage immunity during storms

  # Active Abilities (Compass-Based)
  storm_sense:
    unlock_level: 10
    essence_cost: 1
    cooldown_seconds: 60
    # Particle effect duration in ticks (600 = 30 seconds)
    particle_duration_ticks: 600
    # Ticks between particle spawns
    particle_interval_ticks: 5

  eye_of_the_storm:
    unlock_level: 25
    essence_cost: 500
    cooldown_seconds: 1200     # 20 minutes
    duration_seconds: 600      # 10 minutes
    bubble_radius: 10.0        # Blocks

  stormcaller:
    unlock_level: 40
    essence_cost: 100
    cooldown_seconds: 30
    damage: 5.0
    range: 100.0

  stormclear:
    unlock_level: 50
    essence_cost: 2000
    cooldown_seconds: 3600     # 60 minutes
    push_distance: 1000.0      # How far to push storm
    speed_amplifier: 3         # Speed IV
    speed_duration_seconds: 300 # 5 minutes

# Essence Drain (when passives are active)
drain:
  # Base essence drain per second per active passive
  base_drain_per_second: 1.0

  # Additional drain based on SEL tier
  sel_scaling:
    enabled: true
    # Additional drain % per 10 SEL (e.g., 0.1 = 10% more drain per 10 levels)
    per_10_levels: 0.1

  # Drain multiplier per active passive (stacks multiplicatively)
  # 1 passive = 1.0x, 2 passives = 1.5x, 3 passives = 2.0x
  multi_passive_multiplier: 1.5

  # How often to drain essence (in ticks, 20 = 1 second)
  drain_interval_ticks: 20

# Essence Crafting System
crafting:
  # Amount of essence required to craft a compass
  compass_essence_cost: 100

  # Conversion rate: vault essence to physical essence item
  # (e.g., 10.0 means 10 vault essence = 1 physical essence)
  essence_conversion_rate: 10.0

# Storm Infusion System
infusion:
  # Base ticks required per infusion tier (~5 minutes per tier at default)
  base_ticks_per_tier: 6000

  # Minimum SEL required to use infusion system
  min_sel_for_infusion: 10

  # SEL-based tier caps
  # SEL 10 = Tier 1 (20% protection)
  # SEL 25 = Tier 2 (40% protection)
  # SEL 50 = Tier 3 (60% protection)
  # SEL 75 = Tier 4 (80% protection)
  # SEL 100 = Tier 5 (95% protection)

# Messages
messages:
  prefix: "<gold>[Storm Essence]</gold> "
  essence_gained: "<green>+{amount} Storm Essence! Total: {total} | SEL: {level}</green>"
  passive_enabled: "<green>Enabled {ability}! Essence will drain at {rate}/s</green>"
  passive_disabled: "<yellow>Disabled {ability}. Essence accrual resumed.</yellow>"
  passive_locked: "<red>{ability} requires SEL {required} (you are SEL {current})</red>"
  insufficient_essence: "<red>Not enough essence! {ability} drains {rate}/s</red>"
  status_header: "<gold>━━━ Storm Essence Status ━━━</gold>"
  status_sel: "<aqua>Storm Exposure Level:</aqua> <gold>{level}</gold>"
  status_total: "<aqua>Total Storm Essence Earned:</aqua> <gold>{total}</gold>"
  status_current: "<aqua>Current Essence Balance:</aqua> <gold>{balance}</gold>"
  status_passives: "<aqua>Active Passives:</aqua> <gold>{passives}</gold>"
  status_drain: "<aqua>Essence Drain Rate:</aqua> <gold>{rate}/s</gold>"
